### ISSUE TITLE
insert_backdoor.sh did not work properly

### ISSUE THREAD

**Issue by jourmehr** [airbus-seclab/ilo4_toolbox#20]
hi,
insert_backdoor.sh did not work properly so I patched bootloader and kernel manually with hex editor,
then I changed patch_webserver.py like this:
commenting capestone related code in program because it generated errors.

```Python
def disasm_sc(sc):
    cs = Cs(CS_ARCH_ARM, CS_MODE_ARM)
    for i in cs.disasm(sc, 0):
	   print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
```
after that I manually applied some changes to elf.bin from "outdir folder" like change value from offset 0x188B18 to "D43C1A00"
with hex editor. 
but when I wanted to upload ilo4_250.bin(ilo4_250.bin.backdoored.toflash) from iLO web interface it contained some errors so firmware update process could not complete successfully.

**Comment by alexgzt** [comment]
Hi @jourmehr 

what error did you receive? From the web administration update page?

**Comment by jourmehr** [comment]
Hi @alexgzt 
thanks for your response,
I received this message from administration update page before starting "to flash" operation and after completion of uploading process:
"The last firmware update attempt was not successful, Ready for next update"

**Comment by TheRemote** [comment]
I don't think you did anything wrong here.  I finally got a working Python 2.7 environment built for the scripts that weren't easy to convert.  I was able to run it all successfully including the capstone script.  It was an absolute nightmare to configure this environment and involved "guessing" older versions in pip that would build the wheels without libimport and other errors.

My behavior was identical.  I then found issue #4 which seems to say that they intentionally left this out/broken:

> I noticed in your demo gif when the insert_backdoor.sh script finishes it references a script "exploit_write_flash_page.py". I can't seem to find this script in the code you provide and my version of insert_backdoor.sh simply says "Firmware ready to be flashed" when it completes.

with the answer of:

> I'm sorry but we decided, for security reasons, not to publish this specific exploit to avoid persistent compromise of Internet-facing iLO servers.

This appears to be true.  Even if the backdoor was working you wouldn't be able to use it because there is also another intentionally missing assembly file for backdoor_client.py.  This is mentioned in issue #21 where they again make it clear they didn't release the working exploit code.  

I was especially confused and outright misdirected by https://milo2012.wordpress.com/2018/06/30/some-notes-on-hpe-ilo4-authentication-bypass-and-rce-cve-2017-12542/ where someone wrote up partial notes acting like this worked 100% and recommending to do this.  I'm guessing he posted this then figured out you can't do anything with it because the post ends right after that without a word and was never updated again.  

Security researchers often leave parts like this out to make it so script kiddies can't just copy the scripts and hack a bunch of servers.  Unfortunately the parts left out of this portion of the script are extremely advanced.  It's literally the assembly bytecode for the client that is missing and ASM programming is not easy.  

The first whitepaper will be a total wash for 99% of even intermediate level security researchers/hackers other than getting the user/password which there's a lot of other stuff out there that's easier for that both for learning and practically.

Right now I'm working on their defeating Petya whitepaper which has exactly the kind of stuff I'm interested in:  https://airbus-seclab.github.io/ilo/Whitepaper-Defeating_NotPetya_from_your_iLO4-guinet-perigaud-gazet-czarny.pdf.  Essentially this is low level memory access to the system.  I was hoping to just be able to get a regular "shell" to iLO but it requires the backdoor that is intentionally gutted.

There are a bunch of other files in here from various exploits but outside the README and the slides from their presentations there is no explanation or documentation of any of them.  I'm still sorting through all of it but I'm at least a dozen hours in and just barely got an environment that could even work enough to figure out everything is gutted because these were written in Python at the most awful time of the transition between Python2 and Python3.  

You will have constant issues with these scripts because of it.  I've never had as much environment trouble as with this project even with Go or some of the other languages I roll my eyes at every time I see them knowing it's going to take hours of fighting with old outdated libraries and configuration to even run.

It's been 5 years since this RCE and Shodan is showing less than 100 servers even left with https://www.shodan.io/search?query=%22Server%3A+HPE-iLO-Server%2F1.30%22.  Obviously there's way more than that out there behind firewalls but if they haven't been updated by now they aren't going to be or the second there's a problem they'll just be refreshed/replaced.

I wrote all of this as information for anyone else who is trying to learn about security and not to call out the researchers or team who made this.  If you are trying to learn from this project understand that the environment configuration is a nightmare and the backdoor/RCE isn't actually included.  When you find out what is missing you will have to make a tough decision about whether it's worth it to keep going and invest at least dozens more hours into this and have an excellent chance of still not being able to do anything more than pull the passwords/create an account.

I personally wanted to do more and play with the big features like DMA memory access but it's really too gutted to try it.  You need the backdoor, and they aren't releasing it, probably ever at this point.  Unless you are at the point in your journey where you can reverse engineer/rewrite their assembly code you are better off sticking with the 29 A's and just creating accounts and if that isn't what you wanted to do then it's really of no use to you.  You need to be a card carrying stack smasher to even fix these tools let alone expand them.

Again, no shade on the developers, it is what it is.  The only thing I would say directly to the developers is it has been a really long time since this RCE.  HP is notorious for pushing these old servers out and literally nobody should be running any of this software at this point.  I would *love* to play with and learn about some of the tricks you've done here such as the anti-Petya DMA memory access tricks.  This would be so much greater of a contribution than withholding updates for at this point for <100 (on Shodan) what should be criminally negligent server owners.

**Comment by 0xf4b** [comment]
Hi @TheRemote,

While I don't understand how giving you DMA access would have helped preventing iLO backdoors, let me point you to the stuff you're looking for:
- exploit_write_flash.py has been made public ~3 years ago: https://github.com/airbus-seclab/ilo4_toolbox/blob/master/scripts/iLO4/exploits/exploit_write_flash.py ;
- all the scripts to build a backdoored firmware are also available at https://github.com/airbus-seclab/ilo4_toolbox/tree/master/scripts/iLO4 ;
- finally, @fishilico added his exploit for CVE-2018-7105 providing DMA R/W primitive to the iLO CLI over SSH.

Hi hope this will help you developing this iLO defense framework, feel free to make a pull request when it's done!

Kind regards,

Fabien

**Comment by TheRemote** [comment]
> Hi @TheRemote,
> 
> While I don't understand how giving you DMA access would have helped preventing iLO backdoors
>
Just that by itself wouldn't for sure.  If we have a shell inside iLO though a lot of possibilities open up.  I don't know what the capabilities are yet in there.  I do a lot of ARM work on integrated systems so I'm used to having barebones Linux utilities only on usually a read-only partition as well.

I mean theoretically what couldn't you do?  You have direct access to the server in essentially a separate SoC with a shell into it that can presumably run basic bash scripts.  This is an unimaginable amount of power.  It's designed to be invisible to the server itself.  It's basically god-mode.  I'm sure there are a lot of restrictions but the work you guys have been able to do already is impressive.

I'm still catching up to what all is in here.  This is definitely in my comfort zone going into a shell on this little SoC while writing the ASM is a bit outside my comfort zone (it's on my to-do list, been programming for at least 20 years). 

Thanks for the response and pointing out the resources.  I take back some of what I said earlier, I'm quite passionate about this stuff and I linked to some of the threads that led me to the conclusions I reached but I did note that there's still a lot in here I'm going through.  It does look like the pieces are all here from your links.  Thanks again!

**Comment by anotherpk** [comment]
Hello @0xf4b 
`linux_backdoor.S` seems to have not been made public yet... Still choose to be private?

**Comment by Squall124** [comment]
> Hello @0xf4b `linux_backdoor.S` seems to have not been made public yet... Still choose to be private?

Same question.
Did you find it somewhere somehow ?

**Comment by nikaiw** [comment]
authors decided to keep it private as already answered
